### PR TITLE
Adapt to nix 1.5 changes

### PR DESCRIPTION
**Pull request by gicmo**
- [x] Value -> Variant
- [x] Remove mapping
- [x] Fix tests
  - [x]  TestDataAccess.testOffsetAndCount:219 null
  - [x]  TestDataAccess.testPositionToIndexRangeDimension:137 null
  - [x]  TestDataAccess.testRetrieveData:301 null
  - [x]  TestDataAccess.testTagFeatureData:358 null
  - [x]  TestDataArray.testUnit:110 null
  - [x]  TestDimension.testRangeDimIndexOf:436 null
  - [x]  TestMultiTag.testDataAccess:461 null
  - [x] TestProperty.testUnit:92 null
  - [x] TestTag.testDataAccess:408 null
- [x] deprecated dimension creation
- [x] bindings for new stuff

### CODE REVIEW

**Comment by gicmo** [comment]
@jgrewe maybe you could have a look at the tests failures.

**Comment by jgrewe** [comment]
@gicmo I could not test locally but my guess would be the change in RangeDimension::indexOf which now returns the last index less or equal than offset + extent (at least in the default case)
For the test cases:
* TestDataAccess.testOffsetAndCount:219: second dimension should then be **7**

* TestDataAccess.testPositionToIndexRangeDimension:137 null: should give **2**

* TestDataAccess.testRetrieveData:301 null: (quick guess) again should be **7** for second dim

* TestDataAccess.testTagFeatureData:358 null: tag with pos 5. and extent 2. should give and feature with sampledDim with interval 1. should tag values from index 5 to 7 i.e. the data chunk should be size 1,3 (index returns less or equal than position)

 * TestDimension.testRangeDimIndexOf:436 null: less or equal, thus, index 0
437: index 0
438: index 1
440: index 0 (which is actually not really cool)

* TestMultiTag.testDataAccess:461 null: dim 2 should again be **7**

* TestTag.testDataAccess:408 null: same here, should be **7**

**Comment by gicmo** [comment]
All tests pass now locally.

**Comment by gicmo** [comment]
Should be just remove the deprecated `createXXXDimesion` or live with the compiler warnings (because the corresponding C++ functions are also deprecated)?

**Comment by jgrewe** [comment]
methinks we should simply remove the deprecated methods, same for ```retrieveData```, ```retrieveFeatureData``` methods.

**Pull request merged**
